- name: Deploy Webserver
  hosts: webservers
  become: yes
  vars_files:
    - group_vars/all/vault.yml

  pre_tasks:
    - name: Ping webservers
      ping:

    - name: Install curl
      apt:
        name: curl
        state: present
        update_cache: yes

  roles:
    - webserver
